# Generated by Django 5.2.5 on 2025-11-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposicoes', '0002_slideshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('lancamento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
