# Generated by Django 5.2.5 on 2025-11-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposicoes', '0003_jogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='slug',
            field=models.SlugField(default='default-slideshow', unique=True),
            preserve_default=False,
        ),
    ]
