# Generated by Django 5.2.5 on 2025-11-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposicoes', '0004_slideshow_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='slug',
        ),
    ]
