# Generated by Django 5.2.5 on 2025-11-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposicoes', '0005_remove_slideshow_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='titulo',
            field=models.CharField(default='Sem titulo', max_length=255),
            preserve_default=False,
        ),
    ]
