# Generated by Django 5.2.5 on 2025-11-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposicoes', '0006_slideshow_slug_alter_slideshow_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='slug',
            field=models.SlugField(blank=True, default='default-slideshow', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='titulo',
            field=models.CharField(blank=True, default='Sem título', max_length=255, null=True),
        ),
    ]
